#!/bin/bash

# to calculate something.
# test line2

if [ $# = 0 ]
then
echo
echo "calc script"
echo
echo "A wrap around bc (the linux calculator)."
echo 
echo "bc-syntax:"
echo "echo \"3+4\" |bc -l"
echo
echo "corresponding calc syntax:"
echo "calc \"3+4\""
echo
echo "The quotes may be omitted if bc doesn't need them either."
echo
exit 64
fi

echo $* |bc -l

