#!/bin/bash
#
#
if [ $# = 0 ]
then
echo
echo "makeCTconemask filename"
echo
echo "Make a mask that covers the CT-cone for a specific image."
echo
echo "Usage:"
echo
echo "makeCTconemask <filename.mhd>"
echo
echo "3D images are expected."
echo
exit 64
fi

images=`ls $*`

for im in $images
do
	base=${im%.*}
	ext=${im##*.}
	maskname=$base"_mask."$ext

	dimx=`pxgetimageinformation -in $im -sz -i 0`
	dimy=`pxgetimageinformation -in $im -sz -i 1`
	dimz=`pxgetimageinformation -in $im -sz -i 2`
	spx=`pxgetimageinformation -in $im -sp -i 0`

	centerx=`echo $dimx/2-1 | bc`
	centery=`echo $dimy/2-1 | bc`
	centerz=`echo $dimz/2-1 | bc`
	radius=`echo "($dimx/2-1)*$spx" | bc`

	pxcreatecylinder -in $im -out $maskname -c $centerx $centery $centerz -r $radius
	pxcompressimage $maskname

done



